@extends('layouts.main.main')
@section('nav')
    @include('layouts.main.nav')
@endsection
@section('sidebar')
    @include('layouts.main.sidebar')
@endsection
@section('content')
    @include('layouts.main.content')
@endsection
@section('footer')
    @include('layouts.main.footer')
@endsection